title: "Daily Learning Journal"
description: "A day-wise record of what I study and learn"
theme: jekyll-theme-minimal

author: "Ayush Kumar"
show_downloads: false
repository: StrikerEureka34/StrikerEureka34.github.io

future: true

collections:
  posts:
    output: true
